server:
  port: 8080
spring:
  application:
    name: hotel-management
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  expiry-time: ${EXPIRY_TIME}
  expiry-day: ${EXPIRY_DAY}
  secret-key: ${SECRET_KEY}
  secret-refresh-key: ${SECRET_FRESH_KEY}

integration:
  minio:
    minioAccessKey: ${MINIO_ACCESS_KEY}
    minioSecretKey: ${MINIO_SECRET_KEY}
    minioUrl: ${MINIO_URL}
